bigcartel-themes/luna

source/checkout.html
source/layout.html
source/maintenance.html
source/settings.json

- remove meta keywords/description/social tags

---

source/home.html
source/layout.html

Commit 1: Use alt="" for functional images grouped with associated text
Commit 2: Improve alt text for store logo
[PT Story](https://www.pivotaltracker.com/story/show/169548897)

Update alt text for Luna homepage

---

source/stylesheets/layout.sass

[PT Story](https://www.pivotaltracker.com/story/show/169552572)
**Screenies**

Reenable outline on button focus

---

source/layout.html
source/product.html

[PT Story](https://www.pivotaltracker.com/story/show/169552592)
[Discussion about empty
alt](https://3.basecamp.com/3864451/buckets/14176167/messages/2204920540)
[Resource on "image of"](https://webaim.org/techniques/alttext/)

Update image alt text for product show

---

source/layout.html

Fixes https://www.pivotaltracker.com/story/show/169827712

Add main landmark to homepage

---

source/stylesheets/product.sass

Fixes https://www.pivotaltracker.com/story/show/169552870
(see comments)

Update font size for pogs reset button text

---

source/layout.html
source/stylesheets/layout.sass

Fixes https://www.pivotaltracker.com/story/show/169782573

Update header and footer styles

---

source/stylesheets/layout.sass

Fixes https://www.pivotaltracker.com/story/show/169782573

Decrease text size for "back to site" button

---

source/products.html

Fixes https://www.pivotaltracker.com/story/show/169828506
_______
I chose the text "Category sub-nav" for the aria-label. Does that feel clear?

Add accessible attr to sub-nav

---

source/cart.html

Fixes https://www.pivotaltracker.com/story/show/169827556

Add alt to cart images

---

source/layout.html
source/stylesheets/layout.sass

"More" is too vague to be accessible
Fixes https://www.pivotaltracker.com/story/show/169693344

Replace "more" link with "contact"

---

source/cart.html
source/stylesheets/cart.sass
source/stylesheets/layout.sass
source/stylesheets/product.sass

- Update cart summary font size
- Update quantity input styles
- Apply new font size to all h1
- Update svg for remove item element
Fixes https://www.pivotaltracker.com/story/show/169812455

Update cart styles for text size and contrast

---

source/products.html

This is one step of several needed to make the products pagination
accessible. Other changes will need to be applied in storefront.
[Resource](https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-pagination)
[Another resource](https://www.a11ymatters.com/pattern/pagination/)
Fixes https://www.pivotaltracker.com/story/show/169827401

Wrap pagination in nav

---

source/stylesheets/product.sass

Fixes https://www.pivotaltracker.com/story/show/169999775

Update product status font size

---

source/stylesheets/layout.sass

Fixes https://www.pivotaltracker.com/story/show/169999614

Increase header and footer links font size on mobile

---

source/cart.html
source/stylesheets/cart.sass

Fixes https://www.pivotaltracker.com/story/show/170001634

Make cart image accessible

---

source/stylesheets/product.sass
source/stylesheets/products.sass

Fixes https://www.pivotaltracker.com/story/show/169999775

Increase font size of item status

---

source/stylesheets/products.sass

Fixes https://www.pivotaltracker.com/story/show/169999775

Set mobile font size for product status

---

source/stylesheets/contact.sass

Fixes https://www.pivotaltracker.com/story/show/170077624

Update font sizes on contact form

---

source/stylesheets/layout.sass

Fixes https://www.pivotaltracker.com/story/show/170114888

Increase size of error text

---

source/stylesheets/products.sass

Fixes https://www.pivotaltracker.com/story/show/169846928

Increase category nav font sizes

---

source/layout.html

All content must be contained in landmarks.
Fixes https://www.pivotaltracker.com/story/show/170060356

Move similar products into main landmark

---

source/maintenance.html

Fixes https://www.pivotaltracker.com/story/show/170139491

Wrap body content in main landmark

---

source/cart.html

Title attribute text should not be identical to or very similar to the
element text or alternative text.
Fixes https://www.pivotaltracker.com/story/show/169827557

Remove redundant title attributes

---

source/home.html
source/javascripts/product-option-groups.js
source/layout.html
source/product.html
source/products.html
source/settings.json
source/stylesheets/cart.sass
source/stylesheets/layout.sass
source/stylesheets/product.sass
source/stylesheets/products.sass

- New setting for Header Image Height
- Misc. font size and spacing adjustments
- Rename option to variant
- Improve product form UX
- Remove fade in effect on page load
- New Powered By badge

Web 3386 add new header image size setting to

---

source/layout.html

fix: Update search form with role for accessibility

---

source/home.html
source/layout.html
source/product.html
source/products.html
source/settings.json

feat: add theme setting to hide product options for sold out items

---

source/cart.html
source/javascripts/cart.js
source/stylesheets/cart.sass

- feat: Adds shareable cart link on cart page. Uses web share API if supported, otherwise falls back to copying link to clipboard
- chore: polished wording for empty cart state

feat: shareable cart link on cart page

---

source/layout.html
source/settings.json

- fix: add missing themeColors.backgroundColor for BNPL messaging

Luna v2.16.1

---

source/settings.json

fix: remove unnecessary requirements on image collage settings

Luna 2.20.3
