bigcartel-themes/luna

- source/layout.html
Tested using the ChromeVox extension.
I added the aria-label to each version of the header  nav in order to distinguish
them from the footer nav. The screen reader will now include the aria-label
in its description of the nav. That choice was based on [this MDN
resource](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Navigation_Role)
The footer nav did not need an extra aria-label because it is nested
inside of the footer element, and the screen reader already includes the
word "footer"-- the aria-label would have also said "footer" and been
redundant.
For the screen reader, the role="navigation" attr had to be present in
order for the aria-label to be included in the spoken description.
[PT Story](https://www.pivotaltracker.com/story/show/169550274)
> Add roles and labels to Luna nav

- source/layout.html
This addresses a bug in Apple VoiceOver where the footer content isn't
announced. Assigning it a role of "contentinfo" allows VoiceOver to
recognize it as a footer.
Previously, I had left out an aria-label for the footer nav to avoid
screen reader repetition of the word "footer," but "contentinfo" seems
to work well with aria-label="Footer".
[PT Story](https://www.pivotaltracker.com/story/show/169649155)
[Resource](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer#Accessibility_concerns)
> Add contentinfo role to footer

- source/product.html
- source/stylesheets/_variables.sass
- source/stylesheets/product.sass
The price does not function as a heading-- it is part of the `<h1>`
block as opposed to the beginning of a new section of the page.
[PT Story](https://www.pivotaltracker.com/story/show/169552533)
**Screenies:**
**Before:**
**After:**
> Convert heading to div

- source/layout.html
Fixes https://www.pivotaltracker.com/story/show/169601687
Commit 1: Adds more specificity to vague link text
Commit 2: Assigns button role to link that is acting like a button
Re: `role='button'`, the Search link might need some design attention. I noticed that VO transitions focus easily from the text to the search input, but ChromeVox wasn't able to do that. I wonder if there is a more accessible way to design the Luna search functionality.
> 169601687 accessible link markup

- source/layout.html
- source/product.html
- source/stylesheets/_variables.sass
- source/stylesheets/product.sass
- source/stylesheets/products.sass
Fixes https://www.pivotaltracker.com/story/show/169552870
I chose to add a new variable for font sizes (`$luna-font-base-px`) instead of reusing the `$luna-base` variable. Even though the current value of `$luna-base` could be useful for fonts as well, I didn't want to entangle them, in case margins change in the future while font sizes remain the same.
> Update text sizes on product show

- source/products.html
The text within the link will be read by the screen reader instead. If
the alt tag was also present, the screen reader would read the same info
2x.
Fixes https://www.pivotaltracker.com/story/show/169827431
> Remove alt description from images

- source/stylesheets/layout.sass
Fixes https://www.pivotaltracker.com/story/show/169881422
_____
I noticed this issue when I pushed Luna up to staging.
**Before**
It's a little hard to see, but the button is hanging over the bottom of the banner by 1px.
**After**
> Add margin for announcement close button

- source/cart.html
- source/stylesheets/cart.sass
I set the `id` argument in the input tag to `nil` so that each input
will have a unique id. Currently, all inputs have the same id.
CSS approach from:
https://www.w3.org/WAI/tutorials/forms/labels/#note-on-hiding-elements
Fixes https://www.pivotaltracker.com/story/show/169925599
> Add hidden label to cart quantity inputs

- source/cart.html
- source/stylesheets/cart.sass
Reduces the size constraint to prevent the image from overflowing
the height of the row. `200,200` matches the size of Lunch
Break cart images.
Fixes https://www.pivotaltracker.com/story/show/170001634
> Update image constraint for cart

- source/cart.html
- source/stylesheets/cart.sass
Converting from a link to a button allows users to interact with buttons
with either the space key or enter key-- ie we enable default button
behaviors. This element is a button because it triggers an action and
does not navigate to another page or view.
Fixes https://www.pivotaltracker.com/story/show/169827557
> Convert remove item link to button

- source/cart.html
- source/home.html
- source/products.html
- source/stylesheets/cart.sass
- source/stylesheets/layout.sass
The h1 is available for assistive technologies, but it isn't needed for
design.
Fixes https://www.pivotaltracker.com/story/show/170060356
----
Note: there are other TODOs in that PT story-- I will make separate PRs for them because there are some additional design considerations to follow up on.
> Use class to hide AT-only elements

- source/products.html
- source/stylesheets/layout.sass
- source/stylesheets/products.sass
Because it was a duplicate of the category nav at the top of the product
grid, it violated the rule that landmarks must be unique. It could be
challenging or frustrating for a user relying on accessibility tools to
figure out if there was a difference between the 2 navs. The project
team decided it was okay to remove the second nav.
Fixes https://www.pivotaltracker.com/story/show/170060356
Related to
https://www.pivotaltracker.com/n/projects/1902125/stories/169828506
--------
> Remove bottom category nav

- source/layout.html
In order to distinguish them from one another when using a screen
reader.
Fixes https://www.pivotaltracker.com/story/show/170060356
> Add aria-label to aside landmarks

- source/products.html
- source/settings.json
This was always "Products" which is wrong if you've customized the Products page name in Shop Designer. This change mimics the other themes where it looks for the `search=` query string param to state "Product Search", otherwise the title will be the custom page name.
> fix: `Products` page title correctly reflect search results or custom page name

- source/home.html
- source/settings.json
- source/stylesheets/home.sass
- source/stylesheets/layout.sass
Add support for featured products title on homepage, including "all products" button if there are more products than what is shown as featured.
Added appropriate settings to control each.
> feat: add home featured products title and all products button

- source/products.html
- source/settings.json
- source/stylesheets/products.sass
The category nav does not have a use on search results and is confusing
before
after
> fix: hide category nav on products search results

- source/product.html
- source/settings.json
- source/stylesheets/product.sass
Due to issues with the Facebook share button in some browsers, along with the low engagement on these buttons year over year, the share option is being removed from the theme altogether. Instead, visitors can copy/paste URLs, use browser plugins, or use the native share buttons on mobile browsers.
> Remove social media share buttons

- source/home.html
- source/product.html
- source/products.html
- source/settings.json
- source/stylesheets/layout.sass
- source/stylesheets/product.sass
- source/stylesheets/products.sass
1. Add settings for primary vs secondary product status to be able to differentiate "on sale" vs other statuses
2. Created color combinations for primary vs secondary status for all style presets
3. Slight tweaks to the style presets to make the primary and secondary _background_ colors to be the same to make the presets more broadly appealing by default (vs how most were different)
4. Bump version to 2.8.1
Example from default
> feat: add color settings for primary vs secondary product status

- source/layout.html
- source/settings.json
Allows for 3rd party apps to target key regions for adding content. In particular, key for omnisend and email partners to be able to insert content above the footer.
1. Adds `data-bc-hook` attribute to header and footer
2. Adds `data-bc-page-type` attribute to the body tag
Note: A much larger change was previously proposed but I've scaled it back to only the above 2 changes foregoing the larger change which is much more complex.
> chore: add attributes for data hook on header and footer, and page type in layout

- source/cart.html
- source/home.html
- source/layout.html
- source/product.html
- source/products.html
- source/settings.json
- source/stylesheets/layout.sass
- feat: setting to hide coming soon products
- fix: footer links use secondary text color for consistency with rest of footer
- chore: remove unnecessary bnpl feature flag check 
- chore: bnpl messaging setting respects feature flag
- chore: add `data-bc-hook` for credit
- chore: define section values for theme settings
- chore: add `section` prop to social settings
- chore: reorder settings based on section prop
- chore: reorder featured header setting
- chore: add `plan_type` prop to bnpl setting for future use
- chore: use new feature flag format for visibility
> Luna v2.16.0

- source/javascripts/product-payment-messaging.js
- source/settings.json
- fix: product page BNPL messaging correctly sets background color for stripe popup
> Luna 2.18.1

- source/settings.json
chore: featured categories default to 0 for upgrades
> Luna 2.20.1

- source/home.html
- source/settings.json
fix: skip category collages if grid image style is fit-to-square and single image style
> Luna 2.20.2
